/* pos.js — 獨立 POS 收銀介面（#pos）v0.58 */
(function(){
  const {esc,money,toast,confirmBox}=window.UI,root=()=>document.getElementById('app');
  let cart=[],locationId='',customerId='',lastOrder=null,lastClosedShift=null;
  const rows=()=>DB.products.list().filter(p=>DB.products.isLive(p)).flatMap(p=>p.variants.map(v=>({productId:p.id,variantId:v.id,name:p.name,optionText:Object.values(v.options||{}).join(' / '),sku:v.sku||'',price:v.price,stock:v.stock,image:DB.products.cover(p),color:p.color})));
  const subtotal=()=>cart.reduce((n,x)=>n+x.price*x.qty,0),email=()=>String((DB.admin.user()||{}).email||'').toLowerCase();
  const componentText=x=>(x.components||[]).map(c=>`${c.name}${c.optionText?'・'+c.optionText:''} × ${c.qty}`).join('、');
  function noPerm(){root().innerHTML=`<div class="pos-gate"><div class="gate-card"><h1>沒有 POS 權限</h1><p class="muted">請找店主替這個帳號開啟「POS 收銀」權限。</p><a class="btn" href="#admin">回商家後台</a></div></div>`;}

  async function render(){
    if(!DB.features.pos||!DB.admin.can('pos'))return noPerm();
    const locs=DB.pos.locations().filter(x=>x.enabled);
    if(!locs.length){root().innerHTML=`<div class="pos-gate"><div class="gate-card"><h1>尚未建立門市</h1><a class="btn btn-primary" href="#admin/locations">前往門市管理</a></div></div>`;return;}
    if(!locs.some(x=>x.id===locationId))locationId=(locs.find(x=>x.isDefault)||locs[0]).id;
    let shifts=[];try{shifts=await DB.pos.shifts(100);}catch(e){toast(e.message,'error');}
    const mail=email(),shift=shifts.find(x=>x.status==='open'&&x.locationId===locationId&&(!mail||String(x.cashier||'').toLowerCase()===mail))||(DB.mode==='local'&&shifts.find(x=>x.status==='open'&&x.locationId===locationId));
    root().innerHTML=`<div class="pos-app"><header class="pos-head"><div><b>${esc(DB.settings.get().name)}</b><span>POS 收銀台</span></div><div class="pos-head-actions"><label class="pos-location-label"><span>銷售門市</span><select id="p-location">${locs.map(l=>`<option value="${l.id}" ${l.id===locationId?'selected':''}>${esc(l.name)}</option>`).join('')}</select></label><span class="pill ${shift?'ok':'warn'}">${shift?'已開班':'尚未開班'}</span><button class="btn btn-sm pos-head-btn" id="p-recent">近期交易</button>${shift?`<button class="btn btn-sm pos-head-btn" id="p-cash-event">現金收支</button><button class="btn btn-sm pos-head-btn is-main" id="p-reconcile">當班對帳／交班</button>`:''}<a class="btn btn-sm" href="#admin">商家後台</a></div></header>
      ${lastOrder?`<div class="pos-success"><b>結帳完成</b><span>${esc(lastOrder.number)}・${money(lastOrder.total)}</span><button class="btn btn-sm" id="p-print-last">列印收據</button><button class="btn btn-sm" id="p-success-close">關閉</button></div>`:''}
      ${lastClosedShift?`<section class="pos-close-summary"><div><b>交班完成</b><span>${esc(lastClosedShift.cashier||'')}・差額 ${money((lastClosedShift.actualCash||0)-(lastClosedShift.expectedCash||0))}</span></div><button class="btn btn-sm" id="p-print-shift">列印交班摘要</button><button class="btn btn-sm" id="p-close-summary">關閉</button></section>`:''}
      ${shift?`<section class="pos-shift-strip"><span>本班收銀員 <b>${esc(shift.cashier)}</b></span><span>開班備用金 <b>${money(shift.openingCash)}</b></span><span>現金銷售 <b>${money(shift.cashSales)}</b></span><span>系統應有現金 <b>${money(shift.expectedCash)}</b></span></section>`:`<section class="pos-open"><div><h1>開始今天的收銀</h1><p>請輸入收銀櫃原本的備用金。</p></div><input id="p-opening" type="number" min="0" value="0"><button class="btn btn-primary" id="p-open">開班</button></section>`}
      <main class="pos-work ${shift?'':'is-locked'}"><section class="pos-catalog"><div class="pos-searchbar"><input id="p-search" type="search" placeholder="搜尋商品名稱、規格或 SKU" autofocus><button class="btn btn-primary" id="p-custom">＋ 自訂組合</button></div><div class="pos-grid" id="p-products"></div></section>
      <aside class="pos-bill"><div class="pos-bill-head"><div><b>本次結帳</b><small id="p-lines">0 個品項</small></div><button class="btn btn-sm" id="p-clear">清空</button></div><div class="pos-bill-items" id="p-cart"></div><div class="pos-bill-form"><div class="field"><label>會員（選填）</label><div class="pos-inline"><input id="p-customer-q" placeholder="姓名／手機／Email"><button class="btn btn-sm" id="p-find">搜尋</button></div><select id="p-customer" hidden><option value="">現場散客</option></select><span class="hint" id="p-customer-hint">未選擇會員</span></div><div class="pos-two"><div class="field"><label>整單折扣</label><input id="p-discount" type="number" min="0" value="0"></div><div class="field"><label>付款方式</label><select id="p-pay"><option value="cash">現金</option><option value="card">信用卡（外部刷卡機）</option><option value="mobile">行動支付</option><option value="other">其他</option></select></div></div><div class="pos-cash" id="p-cash-box"><div class="field"><label>實收現金</label><input id="p-received" type="number" min="0" value="0"></div><div><span>找零</span><strong id="p-change">NT$0</strong></div></div><div class="pos-grand"><span>應收</span><strong id="p-total">NT$0</strong></div><button class="pos-submit" id="p-submit" ${shift?'':'disabled'}>完成結帳</button></div></aside></main><div id="p-dialog"></div></div>`;
    bind(shift,rows());
  }

  function bind(shift,products){
    const pbox=document.getElementById('p-products'),cbox=document.getElementById('p-cart'),available=x=>x.bundle?Math.min(...x.components.map(c=>Math.floor(c.stock/c.qty))):x.stock;
    const drawProducts=()=>{const q=document.getElementById('p-search').value.trim().toLowerCase(),list=products.filter(x=>!q||[x.name,x.optionText,x.sku].some(v=>String(v).toLowerCase().includes(q)));pbox.innerHTML=list.length?list.map(x=>`<button class="pos-tile" data-add="${x.variantId}" ${x.stock<=0?'disabled':''}>${x.image?`<img src="${esc(x.image)}" alt="">`:`<i style="background:${esc(x.color)}">${esc(x.name.slice(0,1))}</i>`}<span><b>${esc(x.name)}</b><small>${esc(x.optionText||'單一規格')}</small><em>庫存 ${x.stock}</em><strong>${money(x.price)}</strong></span></button>`).join(''):`<div class="empty">找不到商品</div>`;pbox.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const r=products.find(x=>x.variantId===b.dataset.add),hit=cart.find(x=>!x.bundle&&x.variantId===r.variantId);if(hit){if(hit.qty>=r.stock)return toast('庫存不足','error');hit.qty++;}else cart.push({...r,qty:1});drawCart();});};
    const due=()=>Math.max(0,subtotal()-(+document.getElementById('p-discount').value||0));
    const drawMoney=()=>{const total=due(),received=+document.getElementById('p-received').value||0;document.getElementById('p-total').textContent=money(total);document.getElementById('p-change').textContent=money(Math.max(0,received-total));document.getElementById('p-cash-box').hidden=document.getElementById('p-pay').value!=='cash';};
    const drawCart=()=>{document.getElementById('p-lines').textContent=`${cart.reduce((n,x)=>n+x.qty,0)} 件`;cbox.innerHTML=cart.length?cart.map((x,i)=>`<div class="pos-line"><div><b>${esc(x.name)}</b><small>${esc(x.bundle?componentText(x):x.optionText||'單一規格')}</small></div><div class="pos-step"><button data-minus="${i}" aria-label="減少數量"><span>−</span></button><input data-qty="${i}" type="number" min="1" max="${available(x)}" value="${x.qty}"><button data-plus="${i}" aria-label="增加數量"><span>＋</span></button></div><strong>${money(x.price*x.qty)}</strong><button class="pos-x" data-del="${i}" aria-label="移除">×</button></div>`).join(''):`<div class="pos-empty">點選左邊商品<br>加入本次結帳</div>`;cbox.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{const x=cart[+b.dataset.minus];x.qty>1?x.qty--:cart.splice(+b.dataset.minus,1);drawCart();});cbox.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{const x=cart[+b.dataset.plus],max=available(x);x.qty<max?x.qty++:toast('已達可售數量','error');drawCart();});cbox.querySelectorAll('[data-qty]').forEach(e=>e.onchange=()=>{const x=cart[+e.dataset.qty];x.qty=Math.max(1,Math.min(available(x),Math.floor(+e.value||1)));drawCart();});cbox.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.del,1);drawCart();});drawMoney();};
    drawProducts();drawCart();
    document.getElementById('p-search').oninput=drawProducts;document.getElementById('p-discount').oninput=drawMoney;document.getElementById('p-received').oninput=drawMoney;document.getElementById('p-pay').onchange=drawMoney;document.getElementById('p-clear').onclick=()=>{cart=[];drawCart();};document.getElementById('p-location').onchange=e=>{locationId=e.target.value;cart=[];render();};
    const success=document.getElementById('p-success-close');if(success)success.onclick=()=>{lastOrder=null;render();};const printLast=document.getElementById('p-print-last');if(printLast)printLast.onclick=()=>printReceipt(lastOrder);const closeSummary=document.getElementById('p-close-summary');if(closeSummary)closeSummary.onclick=()=>{lastClosedShift=null;render();};const printShift=document.getElementById('p-print-shift');if(printShift)printShift.onclick=()=>printShiftSummary(lastClosedShift);document.getElementById('p-recent').onclick=recentDialog;const open=document.getElementById('p-open');if(open)open.onclick=async()=>{try{await DB.pos.openShift(locationId,+document.getElementById('p-opening').value||0);toast('開班完成');render();}catch(e){toast(e.message,'error');}};
    if(shift){document.getElementById('p-reconcile').onclick=()=>reconcileDialog(shift);document.getElementById('p-cash-event').onclick=()=>cashDialog(shift);}document.getElementById('p-custom').onclick=()=>bundleDialog(products,drawCart);
    document.getElementById('p-find').onclick=async()=>{const q=document.getElementById('p-customer-q').value.trim();if(!q)return;try{const r=await DB.customers.query({q},{limit:30}),sel=document.getElementById('p-customer');sel.innerHTML='<option value="">現場散客</option>'+(r.rows||[]).map(c=>`<option value="${c.id}">${esc(c.name)}・${esc(c.phone)}</option>`).join('');sel.hidden=false;sel.onchange=()=>{customerId=sel.value;document.getElementById('p-customer-hint').textContent=sel.value?sel.options[sel.selectedIndex].text:'現場散客';};document.getElementById('p-customer-hint').textContent=r.rows.length?`找到 ${r.rows.length} 位會員`:'找不到會員';}catch(e){toast(e.message,'error');}};
    document.getElementById('p-submit').onclick=async e=>{if(!cart.length)return toast('請先加入品項','error');const total=due(),payment=document.getElementById('p-pay').value,received=+document.getElementById('p-received').value||0;if(payment==='cash'&&received<total)return toast('實收現金不足','error');if(!await confirmBox({title:`確認收款 ${money(total)}`,body:payment==='cash'?`實收 ${money(received)}，找零 ${money(received-total)}`:'完成後會建立 POS 訂單並扣除商品庫存。',ok:'完成結帳'}))return;e.target.disabled=true;try{lastOrder=await DB.pos.sale({locationId,shiftId:shift.id,items:cart,discount:+document.getElementById('p-discount').value||0,payment,customerId,note:''});cart=[];customerId='';await render();}catch(err){toast(err.message,'error');e.target.disabled=false;}};
  }

  function bundleDialog(products,redraw){const box=document.getElementById('p-dialog');let chosen={};box.innerHTML=`<div class="pos-modal"><form class="pos-modal-card pos-bundle-card" id="p-custom-form"><h2>建立自訂組合</h2><p class="muted">選擇現有商品，再輸入整組售價；售出後會照數量扣除每項庫存。</p><div class="field"><label>組合名稱</label><input id="pc-name" maxlength="60" required placeholder="例如：母親節禮盒"></div><div class="field"><label>搜尋組合商品</label><input id="pc-search" type="search" placeholder="商品名稱、規格或 SKU"></div><div class="pos-bundle-list" id="pc-products"></div><div class="pos-two"><div class="field"><label>整組售價</label><input id="pc-price" type="number" min="0" max="10000000" required></div><div class="field"><label>組合數量</label><input id="pc-qty" type="number" min="1" max="999" value="1" required></div></div><div class="actions"><button class="btn" type="button" id="pc-cancel">取消</button><button class="btn btn-primary" type="submit">加入結帳</button></div></form></div>`;const draw=()=>{const q=document.getElementById('pc-search').value.toLowerCase(),list=products.filter(x=>!q||`${x.name} ${x.optionText} ${x.sku}`.toLowerCase().includes(q));document.getElementById('pc-products').innerHTML=list.map(x=>`<div class="pos-bundle-row"><div><b>${esc(x.name)}</b><small>${esc(x.optionText||'單一規格')}・庫存 ${x.stock}</small></div><div class="pos-step"><button type="button" data-bminus="${x.variantId}"><span>−</span></button><input readonly value="${chosen[x.variantId]||0}"><button type="button" data-bplus="${x.variantId}" ${x.stock<=0?'disabled':''}><span>＋</span></button></div></div>`).join('')||'<div class="empty">找不到商品</div>';document.querySelectorAll('[data-bminus]').forEach(b=>b.onclick=()=>{chosen[b.dataset.bminus]=Math.max(0,(chosen[b.dataset.bminus]||0)-1);draw();});document.querySelectorAll('[data-bplus]').forEach(b=>b.onclick=()=>{const x=products.find(p=>p.variantId===b.dataset.bplus);chosen[x.variantId]=Math.min(x.stock,(chosen[x.variantId]||0)+1);draw();});};draw();document.getElementById('pc-search').oninput=draw;document.getElementById('pc-cancel').onclick=()=>box.innerHTML='';document.getElementById('p-custom-form').onsubmit=e=>{e.preventDefault();const name=document.getElementById('pc-name').value.trim(),price=Math.round(+document.getElementById('pc-price').value||0),qty=Math.floor(+document.getElementById('pc-qty').value||0),components=products.filter(x=>chosen[x.variantId]>0).map(x=>({...x,qty:chosen[x.variantId]}));if(!components.length)return toast('請至少選擇一項現有商品','error');if(!name||qty<1||price<0)return toast('請填寫完整的組合名稱、售價與數量','error');const max=Math.min(...components.map(c=>Math.floor(c.stock/c.qty)));if(qty>max)return toast(`組合庫存最多可售 ${max} 組`,'error');cart.push({bundle:true,id:'bundle_'+Date.now(),name,price,qty,components});box.innerHTML='';redraw();};}

  function cashDialog(shift){const box=document.getElementById('p-dialog');box.innerHTML=`<div class="pos-modal"><form class="pos-modal-card" id="p-cash-form"><h2>登記現金收支</h2><p class="muted">非銷售的現金放入或取出都要登記，交班對帳才會正確。</p><div class="field"><label>收支類型</label><select id="pe-kind"><option value="in">放入現金</option><option value="out">取出現金</option></select></div><div class="field"><label>金額</label><input id="pe-amount" type="number" min="1" required></div><div class="field"><label>原因</label><input id="pe-reason" maxlength="200" required placeholder="例如：購買耗材"></div><div class="actions"><button class="btn" type="button" id="pe-cancel">取消</button><button class="btn btn-primary" type="submit">完成登記</button></div></form></div>`;document.getElementById('pe-cancel').onclick=()=>box.innerHTML='';document.getElementById('p-cash-form').onsubmit=async e=>{e.preventDefault();try{await DB.pos.cashEvent(shift.id,document.getElementById('pe-kind').value,+document.getElementById('pe-amount').value,document.getElementById('pe-reason').value.trim());toast('現金收支已登記');box.innerHTML='';render();}catch(err){toast(err.message,'error');}};}
  function reconcileDialog(shift){
    const box=document.getElementById('p-dialog');
    box.innerHTML=`<div class="pos-modal"><form class="pos-modal-card pos-reconcile" id="p-reconcile-form"><h2>當班對帳／交接班</h2><p class="muted">輸入實際點到的現金，按下完成後會直接結班，並同步至後台「班別與日結」。</p><div class="pos-reconcile-grid"><span>開班備用金<b>${money(shift.openingCash)}</b></span><span>現金銷售<b>＋ ${money(shift.cashSales)}</b></span><span>現金退款<b>－ ${money(shift.cashRefunds)}</b></span><span>放入／取出<b>${money(shift.cashIn)}／${money(shift.cashOut)}</b></span></div><div class="pos-expected"><span>系統應有現金</span><strong>${money(shift.expectedCash)}</strong></div><div class="field"><label>實際點到的現金</label><input id="pr-actual" type="number" min="0" value="${shift.expectedCash}" required></div><div class="pos-difference"><span>對帳結果</span><strong id="pr-diff"></strong></div><div class="field"><label>交班備註（選填）</label><textarea id="pr-note" maxlength="500" rows="3"></textarea></div><div class="pos-close-note">提醒：完成後本班會立即結束，若要繼續收銀需重新開班。</div><div class="actions"><button class="btn" type="button" id="pr-cancel">繼續當班</button><button class="btn btn-primary" type="submit" id="pr-submit">完成交班並結班</button></div></form></div>`;
    const diff=()=>{const d=(+document.getElementById('pr-actual').value||0)-shift.expectedCash,el=document.getElementById('pr-diff');el.textContent=(d>0?'多收 ':d<0?'短少 ':'相符 ')+money(Math.abs(d));el.className=d===0?'ok':d>0?'more':'short';};
    diff();document.getElementById('pr-actual').oninput=diff;document.getElementById('pr-cancel').onclick=()=>box.innerHTML='';
    let submitting=false;
    document.getElementById('p-reconcile-form').onsubmit=async e=>{e.preventDefault();if(submitting)return;const actual=+document.getElementById('pr-actual').value,note=document.getElementById('pr-note').value.trim(),submit=document.getElementById('pr-submit');if(actual<0)return toast('實際現金不能小於 0','error');submitting=true;submit.disabled=true;submit.textContent='結班處理中…';try{const r=await DB.pos.closeShift(shift.id,actual,note);lastClosedShift={...shift,...r,actualCash:actual,note};toast(`交班完成・差額 ${money(r.actualCash-r.expectedCash)}`);cart=[];box.innerHTML='';await render();}catch(err){submitting=false;submit.disabled=false;submit.textContent='完成交班並結班';toast(err.message,'error');}};
  }
  function posOrders(){return DB.orders.list().filter(o=>(o.channel||'online')==='pos'&&(!locationId||o.locationId===locationId)).slice(0,20);}
  function receiptHtml(o){return `<div class="pos-receipt"><h2>${esc(DB.settings.get().name)}</h2><p>POS 收據<br>${esc(o.number||o.id||'')}<br>${esc(new Date(o.createdAt||Date.now()).toLocaleString('zh-TW'))}</p><hr>${(o.items||[]).map(i=>`<div><span>${esc(i.name)} × ${i.qty}</span><b>${money(i.price*i.qty)}</b></div>`).join('')}<hr><div class="total"><span>合計</span><b>${money(o.total)}</b></div><p>付款：${esc((o.payment||{}).methodName||(o.payment||{}).methodId||'')}</p><p>謝謝您的購買</p></div>`;}
  function printReceipt(o){if(!o)return;const box=document.getElementById('p-dialog');box.innerHTML=`<div class="pos-modal"><div class="pos-modal-card">${receiptHtml(o)}<div class="actions"><button class="btn" id="receipt-close">關閉</button><button class="btn btn-primary" id="receipt-print">列印</button></div></div></div>`;document.getElementById('receipt-close').onclick=()=>box.innerHTML='';document.getElementById('receipt-print').onclick=()=>window.print();}
  function recentDialog(){const box=document.getElementById('p-dialog'),list=posOrders();box.innerHTML=`<div class="pos-modal"><div class="pos-modal-card pos-recent-card"><h2>近期 POS 交易</h2><p class="muted">如需退款或作廢，請進商家後台開啟該筆訂單，避免誤操作。</p><div class="pos-recent-list">${list.length?list.map(o=>`<div><span><b>${esc(o.number)}</b><small>${esc(new Date(o.createdAt).toLocaleString('zh-TW'))}</small></span><strong>${money(o.total)}</strong><button class="btn btn-sm" data-receipt="${o.id}">收據</button><a class="btn btn-sm" href="#admin/order/${o.id}">售後</a></div>`).join(''):'<div class="empty">目前沒有 POS 交易</div>'}</div><div class="actions"><button class="btn" id="recent-close">關閉</button></div></div></div>`;document.getElementById('recent-close').onclick=()=>box.innerHTML='';box.querySelectorAll('[data-receipt]').forEach(b=>b.onclick=()=>printReceipt(list.find(o=>o.id===b.dataset.receipt)));}
  function printShiftSummary(s){if(!s)return;const box=document.getElementById('p-dialog'),diff=(s.actualCash||0)-(s.expectedCash||0);box.innerHTML=`<div class="pos-modal"><div class="pos-modal-card pos-receipt"><h2>交班摘要</h2><p>${esc(DB.settings.get().name)}<br>收銀員：${esc(s.cashier||'')}<br>結班：${esc(new Date().toLocaleString('zh-TW'))}</p><hr><div><span>開班備用金</span><b>${money(s.openingCash||0)}</b></div><div><span>現金銷售</span><b>${money(s.cashSales||0)}</b></div><div><span>系統應有</span><b>${money(s.expectedCash||0)}</b></div><div><span>實際現金</span><b>${money(s.actualCash||0)}</b></div><div class="total"><span>差額</span><b>${money(diff)}</b></div><p>${esc(s.note||'')}</p><div class="actions"><button class="btn" id="shift-print-close">關閉</button><button class="btn btn-primary" id="shift-print-do">列印</button></div></div></div>`;document.getElementById('shift-print-close').onclick=()=>box.innerHTML='';document.getElementById('shift-print-do').onclick=()=>window.print();}
  window.PosApp=async function(){await render();window.scrollTo(0,0);};
})();
